### ISSUE TITLE
Pickup Time to be 15 minute increment

### ISSUE THREAD

**Issue by mbachmeier** [Code-4-Group/safewalk-issue-tracker#4]
Pickup Time should be 15m increments and start at next 15m + current time.
First option is correct with 'ASAP'.

**Comment by mbachmeier** [comment]
Not sure how to re-open the issue OR if just start a new issue.

Still fails when starting from the current time. Appears to always start at 01:00pm.

Example: 
Current time is 08:47a. First option would be 'ASAP', and then 09:00a, 09:15a, ...

**Comment by hans-lts** [comment]
Resolved
